show databases;
use assignment_2;

show tables;

select *
from emp;

select *
from dept;

#QUERY-1
SELECT ENAME
FROM EMP 
WHERE SAL=(SELECT MAX(SAL)
FROM EMP);

#QUERY-2
SELECT ENAME
FROM EMP 
WHERE (SAL,JOB)=(SELECT MAX(SAL),JOB
FROM EMP
WHERE JOB='Salesman') ;

#QUERY-3
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO
FROM EMP
GROUP BY DEPTNO
HAVING (AVG(SAL),DEPTNO)=(SELECT MAX(AVG(SAL)),DEPTNO
FROM (SELECT AVG(sal), deptno
FROM emp
GROUP BY deptno) AS avgEmp));

SELECT DNAME
FROM DEPT
WHERE DEPTNO IN ( SELECT DEPTNO
FROM EMP
GROUP BY DEPTNO
HAVING AVG(SAL)>=ALL(SELECT AVG(SAL)
FROM EMP
GROUP BY DEPTNO));

#QUERY-4
SELECT ENAME
FROM EMP
WHERE SAL>(SELECT SAL
FROM EMP
WHERE ENAME='Turner');

#QUERY-5
SELECT ENAME
FROM EMP
WHERE HIREDATE>(SELECT HIREDATE
FROM EMP
WHERE ENAME='Allen');

#QUERY-6
SELECT DNAME
FROM DEPT
WHERE DEPTNO=(SELECT DEPTNO
FROM EMP
WHERE ENAME='Ford');

#QUERY-7
SELECT LOC 
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO
FROM EMP
WHERE ENAME='Smith');

#QUERY-8
SELECT ENAME 
FROM EMP 
WHERE EMPNO NOT IN (SELECT DISTINCT MGR 
FROM EMP 
WHERE MGR IS NOT NULL);

#QUERY-9
SELECT ENAME
FROM EMP
WHERE DEPTNO=(SELECT DEPTNO
FROM DEPT
WHERE DNAME='Research') AND HIREDATE<'2007-07-30';

#QUERY-10
SELECT MAX(SAL)
FROM EMP
WHERE SAL<(SELECT MAX(SAL)
FROM EMP);

#QUERY-11
SELECT ENAME
FROM EMP
WHERE SAL=(SELECT MAX(SAL)
FROM EMP
WHERE SAL<(SELECT MAX(SAL)
FROM EMP));

#QUERY-12
SELECT MIN(SAL)
FROM (SELECT  DISTINCT SAL
FROM EMP
ORDER BY SAL DESC
LIMIT 5) AS T;

#QUERY-13
SELECT ENAME
FROM EMP
WHERE SAL>=(SELECT  MIN(SAL)
FROM (SELECT SAL
FROM EMP
ORDER BY SAL DESC
LIMIT 5) AS T);

SELECT ENAME
FROM EMP
ORDER BY SAL DESC
LIMIT 5;

#QUERY-14
SELECT ENAME
FROM EMP
WHERE SAL>(SELECT MAX(SAL)
FROM EMP
WHERE DEPTNO=(SELECT DEPTNO
FROM DEPT
WHERE LOC='Dallas'));

#QUERY-15
SELECT DNAME
FROM DEPT
WHERE DEPTNO NOT IN (SELECT DISTINCT DEPTNO
FROM EMP);

#QUERY-16
SELECT ENAME
FROM EMP
WHERE HIREDATE=(SELECT HIREDATE
FROM EMP
WHERE ENAME='Adams') AND ENAME!='Adams';

#QUERY-17
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO
FROM EMP
WHERE COMM IS NOT NULL);

#QUERY-18
SELECT DEPTNO,ENAME
FROM EMP
WHERE (DEPTNO,SAL) IN (SELECT DEPTNO,MIN(SAL)
FROM EMP
GROUP BY DEPTNO);

SELECT DEPTNO,ENAME
FROM EMP E1
WHERE SAL=(SELECT MIN(SAL)
FROM EMP E2
WHERE E1.DEPTNO=E2.DEPTNO);


-- -------------------PART-B---------------------

#QUERY-1
SELECT MGR,MIN(SAL)
FROM EMP
WHERE MGR IS NOT NULL
GROUP BY MGR
HAVING MIN(SAL)>1000
ORDER BY SAL DESC;

#QUERY-2
SELECT DNAME,LOC,COUNT(DISTINCT EMPNO),AVG(SAL)
FROM DEPT D,EMP E
WHERE D.DEPTNO=E.DEPTNO
GROUP BY E.DEPTNO;

#QUERY-3
SELECT E1.ENAME EMPLOYEE,E1.EMPNO AS 'EMP#',E2.ENAME MANAGER,E2.EMPNO 'MGR#'
FROM EMP E1
LEFT JOIN EMP E2
ON E1.MGR=E2.EMPNO;

#QUERY-4
SELECT MAX(SAL)-MIN(SAL) AS DIFFERENCE
FROM EMP;

#QUERY-5
SELECT DEPTNO,(MAX(SAL)-MIN(SAL)) AS DIFF
FROM EMP
GROUP BY DEPTNO;

#QUERY-6
SELECT E1.ENAME EMPLOYEE,E1.HIREDATE 'EMP HIREDATE',E2.ENAME MANAGER,E2.HIREDATE 'MGR HIREDATE'
FROM EMP E1,EMP E2
WHERE E1.MGR=E2.EMPNO AND E2.HIREDATE>E1.HIREDATE;